// Question bank for the grammar practice site.
// type "mc"   -> options[] + answer (exact string match to one option)
// type "fill" -> answers[] (array of accepted strings, matched case-insensitively, trimmed)

const TOPICS = [
  {
    id: "be",
    name: "Verb 'To Be'",
    icon: "🧍",
    description: "am / is / are — statements, negatives, questions",
    questions: [
      { type: "mc", q: "I ___ a teacher.", options: ["am", "is", "are"], answer: "am", exp: "Use 'am' with I." },
      { type: "mc", q: "She ___ from Ukraine.", options: ["am", "is", "are"], answer: "is", exp: "Use 'is' with she/he/it." },
      { type: "mc", q: "They ___ my neighbors.", options: ["am", "is", "are"], answer: "are", exp: "Use 'are' with we/you/they." },
      { type: "mc", q: "He ___ a tattoo artist.", options: ["am", "is", "are"], answer: "is", exp: "He → is." },
      { type: "mc", q: "We ___ ready.", options: ["am", "is", "are"], answer: "are", exp: "We → are." },
      { type: "mc", q: "It ___ cold today.", options: ["am", "is", "are"], answer: "is", exp: "It → is." },
      { type: "mc", q: "You ___ very kind.", options: ["am", "is", "are"], answer: "are", exp: "You → are." },
      { type: "mc", q: "Marco ___ tall.", options: ["am", "is", "are"], answer: "is", exp: "Marco = he → is." },
      { type: "mc", q: "The twins ___ noisy.", options: ["am", "is", "are"], answer: "are", exp: "Plural subject → are." },
      { type: "mc", q: "I ___ not tired.", options: ["am", "is", "are"], answer: "am", exp: "I → am." },
      { type: "mc", q: "She ___ at home. (negative)", options: ["isn't", "aren't", "am not"], answer: "isn't", exp: "she + is not → isn't." },
      { type: "mc", q: "They ___ ready yet. (negative)", options: ["aren't", "isn't", "am not"], answer: "aren't", exp: "they + are not → aren't." },
      { type: "mc", q: "___ you ready? (question)", options: ["Am", "Is", "Are"], answer: "Are", exp: "you → Are you...?" },
      { type: "mc", q: "___ she a doctor? (question)", options: ["Am", "Is", "Are"], answer: "Is", exp: "she → Is she...?" },
      { type: "mc", q: "___ they students? (question)", options: ["Am", "Is", "Are"], answer: "Are", exp: "they → Are they...?" },
      { type: "mc", q: "I ___ from Kyiv.", options: ["am", "is", "are"], answer: "am", exp: "I → am." },
      { type: "mc", q: "The flamingo ___ pink.", options: ["am", "is", "are"], answer: "is", exp: "Singular subject → is." },
      { type: "mc", q: "My cats ___ cute.", options: ["am", "is", "are"], answer: "are", exp: "Plural subject → are." },
      { type: "mc", q: "It ___ my phone.", options: ["am", "is", "are"], answer: "is", exp: "It → is." },
      { type: "mc", q: "We ___ happy.", options: ["am", "is", "are"], answer: "are", exp: "We → are." },
      { type: "mc", q: "___ I late? (question)", options: ["Am", "Is", "Are"], answer: "Am", exp: "I → Am I...?" },
      { type: "mc", q: "He ___ busy. (negative)", options: ["isn't", "aren't", "am not"], answer: "isn't", exp: "he + is not → isn't." },
      { type: "mc", q: "You ___ my student.", options: ["am", "is", "are"], answer: "are", exp: "You → are." },
      { type: "mc", q: "Sarah ___ a nurse.", options: ["am", "is", "are"], answer: "is", exp: "Sarah = she → is." },
      { type: "mc", q: "The books ___ on the table.", options: ["am", "is", "are"], answer: "are", exp: "Plural subject → are." }
    ]
  },
  {
    id: "present-simple",
    name: "Present Simple",
    icon: "🔁",
    description: "Habits, routines, general truths, likes/dislikes",
    questions: [
      { type: "fill", q: "Mia ___ (wake) up at 6am.", answers: ["wakes"], exp: "he/she/it → add -s." },
      { type: "fill", q: "Marco ___ (own) a small restaurant.", answers: ["owns"], exp: "he/she/it → add -s." },
      { type: "fill", q: "The twins ___ (not / watch) football.", answers: ["don't watch", "do not watch"], exp: "they → don't + base verb." },
      { type: "fill", q: "My wife always ___ (brush) her teeth.", answers: ["brushes"], exp: "she → brushes (add -es after sh)." },
      { type: "fill", q: "I ___ (like) carrot juice.", answers: ["like"], exp: "I → base verb, no -s." },
      { type: "fill", q: "Sarah ___ (not / like) dogs.", answers: ["doesn't like", "does not like"], exp: "she → doesn't + base verb." },
      { type: "fill", q: "___ she ___ (work) every day?", answers: ["does she work"], exp: "Question with she → does she + base verb." },
      { type: "fill", q: "___ you ___ (like) tea?", answers: ["do you like"], exp: "Question with you → do you + base verb." },
      { type: "fill", q: "He ___ (go) to work sometimes.", answers: ["goes"], exp: "he → goes (irregular -es)." },
      { type: "fill", q: "Water ___ (boil) at 100°C.", answers: ["boils"], exp: "General truth, it → boils." },
      { type: "fill", q: "The sun ___ (rise) in the east.", answers: ["rises"], exp: "General truth, it → rises." },
      { type: "fill", q: "Pickles the cat sometimes ___ (grab) my socks.", answers: ["grabs"], exp: "he/she/it → grabs." },
      { type: "fill", q: "My neighbors ___ (not / watch) football.", answers: ["don't watch", "do not watch"], exp: "they → don't + base verb." },
      { type: "fill", q: "Does Marco own a restaurant? Yes, he ___.", answers: ["does"], exp: "Short answer with does." },
      { type: "fill", q: "He ___ (want) a table for three.", answers: ["wants"], exp: "he → wants." },
      { type: "fill", q: "I ___ (not / know) his number.", answers: ["don't know", "do not know"], exp: "I → don't + base verb." },
      { type: "fill", q: "She ___ (know) his number.", answers: ["knows"], exp: "she → knows." },
      { type: "fill", q: "We ___ (want) a table for four.", answers: ["want"], exp: "we → base verb, no -s." },
      { type: "fill", q: "The flamingo ___ (eat) fish.", answers: ["eats"], exp: "it → eats." },
      { type: "fill", q: "___ they ___ (work) every day?", answers: ["do they work"], exp: "Question with they → do they + base verb." },
      { type: "fill", q: "Alicia ___ (play) tennis every Saturday.", answers: ["plays"], exp: "she → plays." },
      { type: "fill", q: "My cat ___ (love) to sleep.", answers: ["loves"], exp: "it → loves." },
      { type: "fill", q: "___ he ___ (like) tea?", answers: ["does he like"], exp: "Question with he → does he + base verb." },
      { type: "fill", q: "I ___ (go) to the gym twice a week.", answers: ["go"], exp: "I → base verb, no -s." },
      { type: "fill", q: "She ___ (teach) math at school.", answers: ["teaches"], exp: "she → teaches (add -es after ch)." },
      { type: "fill", q: "It ___ (rain) a lot in April.", answers: ["rains"], exp: "it → rains." },
      { type: "fill", q: "They ___ (not / live) here anymore.", answers: ["don't live", "do not live"], exp: "they → don't + base verb." },
      { type: "fill", q: "He ___ (have) a house.", answers: ["has"], exp: "Irregular: have → has." },
      { type: "mc", q: "Choose the correct question:", options: ["Does she works every day?", "Does she work every day?", "Do she work every day?"], answer: "Does she work every day?", exp: "Does + subject + base verb (no -s)." },
      { type: "mc", q: "Choose the correct negative:", options: ["He don't like coffee.", "He doesn't likes coffee.", "He doesn't like coffee."], answer: "He doesn't like coffee.", exp: "doesn't + base verb, no extra -s." }
    ]
  },
  {
    id: "frequency",
    name: "Adverbs of Frequency",
    icon: "⏱️",
    description: "always, usually, often, sometimes, rarely, never...",
    questions: [
      { type: "mc", q: "I ___ (100%) wake up at 7.", options: ["always", "sometimes", "never"], answer: "always", exp: "100% = always." },
      { type: "mc", q: "Mia ___ (90%) has guitar lessons on Fridays.", options: ["usually", "rarely", "never"], answer: "usually", exp: "90% = usually." },
      { type: "mc", q: "The twins ___ (70%) compete with each other.", options: ["often", "hardly ever", "always"], answer: "often", exp: "70% = often." },
      { type: "mc", q: "Pickles ___ (50%) grabs my socks.", options: ["sometimes", "always", "never"], answer: "sometimes", exp: "50% = sometimes." },
      { type: "mc", q: "My cousin's pig ___ (10%) stays clean.", options: ["hardly ever", "usually", "often"], answer: "hardly ever", exp: "10% = hardly ever." },
      { type: "mc", q: "I ___ (5%) eat junk food.", options: ["rarely", "always", "usually"], answer: "rarely", exp: "5% = rarely." },
      { type: "mc", q: "They ___ (0%) see the ocean.", options: ["never", "always", "often"], answer: "never", exp: "0% = never." },
      { type: "mc", q: "Choose the correct sentence:", options: ["She always is happy.", "She is always happy.", "Always she is happy."], answer: "She is always happy.", exp: "With 'to be', the adverb goes AFTER it." },
      { type: "mc", q: "Choose the correct sentence:", options: ["I sometimes am late.", "I am sometimes late.", "Sometimes am I late."], answer: "I am sometimes late.", exp: "With 'to be', the adverb goes AFTER it." },
      { type: "mc", q: "Choose the correct sentence:", options: ["He goes never to the gym.", "He never goes to the gym.", "He goes to the gym never."], answer: "He never goes to the gym.", exp: "With normal verbs, the adverb goes BEFORE the verb." },
      { type: "mc", q: "Choose the correct sentence:", options: ["They usually eat breakfast at 8.", "They eat usually breakfast at 8.", "Usually eat they breakfast at 8."], answer: "They usually eat breakfast at 8.", exp: "The adverb goes before the main verb." },
      { type: "fill", q: "Are you ___ (50%) tired after work?", answers: ["sometimes"], exp: "50% = sometimes." },
      { type: "fill", q: "Marco isn't ___ (100%) at the restaurant.", answers: ["always"], exp: "100% = always." },
      { type: "fill", q: "The twins aren't ___ (90%) noisy.", answers: ["usually"], exp: "90% = usually." },
      { type: "mc", q: "\"Twice a week\" means...", options: ["very often", "not very often", "never"], answer: "not very often", exp: "Twice a week is a low frequency." },
      { type: "mc", q: "\"Every day\" means...", options: ["always", "rarely", "sometimes"], answer: "always", exp: "Every day = always." },
      { type: "mc", q: "\"Once a year\" means...", options: ["often", "rarely", "always"], answer: "rarely", exp: "Once a year is very infrequent → rarely." },
      { type: "fill", q: "I go to the gym ___ a week. (2 times)", answers: ["twice"], exp: "2 times = twice." },
      { type: "mc", q: "Choose the correct question:", options: ["Do you ever exercise?", "Ever you do exercise?"], answer: "Do you ever exercise?", exp: "Do + subject + ever + base verb." },
      { type: "fill", q: "She ___ (0%) drinks coffee.", answers: ["never"], exp: "0% = never." },
      { type: "fill", q: "My neighbors ___ (0%) watch football.", answers: ["never"], exp: "0% = never." },
      { type: "mc", q: "He goes to the gym three times a month. This means he goes...", options: ["often", "rarely", "always"], answer: "rarely", exp: "Three times a month is infrequent → rarely." }
    ]
  },
  {
    id: "demonstratives",
    name: "This / These / That / Those",
    icon: "👉",
    description: "Near vs. far, singular vs. plural",
    questions: [
      { type: "mc", q: "___ apple in my hand is sweet.", options: ["This", "These", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "___ people over there must go to another room.", options: ["This", "These", "Those"], answer: "Those", exp: "Far + plural → those." },
      { type: "mc", q: "I need ___ item right now, in my hands.", options: ["this", "these", "those"], answer: "this", exp: "Near + singular → this." },
      { type: "mc", q: "___ shoes across the room are dirty.", options: ["This", "That", "Those"], answer: "Those", exp: "Far + plural → those." },
      { type: "mc", q: "___ cup in my hand is empty.", options: ["This", "That", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "___ mountains far away are beautiful.", options: ["This", "These", "Those"], answer: "Those", exp: "Far + plural → those." },
      { type: "mc", q: "___ pen right here is broken.", options: ["This", "These", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "___ car across the street is red.", options: ["This", "That", "These"], answer: "That", exp: "Far + singular → that." },
      { type: "mc", q: "___ students standing next to me are my classmates.", options: ["This", "These", "Those"], answer: "These", exp: "Near + plural → these." },
      { type: "mc", q: "Look at ___ birds flying far away!", options: ["this", "these", "those"], answer: "those", exp: "Far + plural → those." },
      { type: "mc", q: "___ soup in front of me is too hot.", options: ["This", "That", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "I don't like ___ shoes in the window over there.", options: ["this", "these", "those"], answer: "those", exp: "Far + plural → those." },
      { type: "mc", q: "___ is my house. (pointing at a house right here)", options: ["This", "These", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "___ are my keys, right here in my hand.", options: ["This", "These", "Those"], answer: "These", exp: "Near + plural → these." },
      { type: "mc", q: "___ was a great movie we watched last month.", options: ["This", "That", "These"], answer: "That", exp: "Referring back to something in the past → that." },
      { type: "mc", q: "Can I have ___ apples, over there near you?", options: ["this", "these", "those"], answer: "those", exp: "Far + plural → those." },
      { type: "mc", q: "___ phone I'm holding is new.", options: ["This", "That", "Those"], answer: "This", exp: "Near + singular → this." },
      { type: "mc", q: "Choose the plural, near form:", options: ["this", "these", "those"], answer: "these", exp: "Near + plural → these." },
      { type: "mc", q: "Choose the singular, far form:", options: ["that", "these", "this"], answer: "that", exp: "Far + singular → that." },
      { type: "mc", q: "___ books on my desk right now are mine.", options: ["This", "These", "Those"], answer: "These", exp: "Near + plural → these." }
    ]
  },
  {
    id: "articles",
    name: "Articles: a / an / the",
    icon: "📰",
    description: "Sound rules, first mention vs. specific, generalizing",
    questions: [
      { type: "mc", q: "I saw ___ dog.", options: ["a", "an", "the"], answer: "a", exp: "Consonant sound → a." },
      { type: "mc", q: "She is ___ engineer.", options: ["a", "an", "the"], answer: "an", exp: "Vowel sound (e) → an." },
      { type: "mc", q: "He waited for ___ hour.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "That's ___ honest answer.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "It's ___ university.", options: ["a", "an", "the"], answer: "a", exp: "Starts with a 'yoo' (consonant) sound → a." },
      { type: "mc", q: "I need ___ umbrella.", options: ["a", "an", "the"], answer: "an", exp: "Vowel sound (u) → an." },
      { type: "mc", q: "He works as ___ accordion player.", options: ["a", "an", "the"], answer: "an", exp: "Job/role, vowel sound → an." },
      { type: "mc", q: "I bought ___ pizza slice.", options: ["a", "an", "the"], answer: "a", exp: "One of many → a." },
      { type: "mc", q: "Apples cost $5 ___ pound.", options: ["a", "an", "the"], answer: "a", exp: "Per/each → a." },
      { type: "mc", q: "I saw ___ puppy in the park.", options: ["a", "an", "the"], answer: "a", exp: "First mention → a." },
      { type: "mc", q: "Give me ___ puppy, please. (the one I just saw)", options: ["a", "an", "the"], answer: "the", exp: "Now specific/already mentioned → the." },
      { type: "mc", q: "Can you pass me ___ salt?", options: ["a", "an", "the"], answer: "the", exp: "Specific, known item → the." },
      { type: "mc", q: "She has ___ great idea.", options: ["a", "an", "the"], answer: "a", exp: "One of many ideas → a." },
      { type: "mc", q: "He is ___ honest man.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "I need ___ hour to finish this.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "That's ___ university student.", options: ["a", "an", "the"], answer: "a", exp: "'Yoo' sound is a consonant sound → a." },
      { type: "mc", q: "Let's grab ___ pizza.", options: ["a", "an", "the"], answer: "a", exp: "General suggestion → a." },
      { type: "mc", q: "___ sun is bright today.", options: ["A", "An", "The"], answer: "The", exp: "There is only one sun → the." },
      { type: "mc", q: "Choose the correct generalizing sentence:", options: ["Cats are cute.", "The cats are cute.", "A cats are cute."], answer: "Cats are cute.", exp: "No article for general statements about plural things." },
      { type: "mc", q: "___ Earth orbits the sun.", options: ["A", "An", "The"], answer: "The", exp: "There is only one Earth → the." },
      { type: "mc", q: "I work as ___ teacher.", options: ["a", "an", "the"], answer: "a", exp: "Job/role, consonant sound → a." },
      { type: "mc", q: "He bought an apple. Then he ate ___ apple. (the one he bought)", options: ["a", "an", "the"], answer: "the", exp: "Now specific → the." },
      { type: "mc", q: "Can you open ___ door? (the one we both know)", options: ["a", "an", "the"], answer: "the", exp: "Specific, known door → the." },
      { type: "mc", q: "She wants to be ___ actress one day.", options: ["a", "an", "the"], answer: "an", exp: "Vowel sound (a) → an." },
      { type: "mc", q: "This is ___ elephant.", options: ["a", "an", "the"], answer: "an", exp: "Vowel sound (e) → an." },
      { type: "mc", q: "I need ___ new chair for my kitchen.", options: ["a", "an", "the"], answer: "a", exp: "One of many, consonant sound (n in 'new') → a." },
      { type: "mc", q: "Choose the correct generalizing sentence:", options: ["Water is important for life.", "The water is important for life.", "A water is important for life."], answer: "Water is important for life.", exp: "No article for general statements about uncountable things." },
      { type: "mc", q: "She is ___ university student studying medicine.", options: ["a", "an", "the"], answer: "a", exp: "'Yoo' sound is a consonant sound → a." }
    ]
  },
  {
    id: "possessives",
    name: "Possessive Adjectives",
    icon: "🔑",
    description: "my, your, his, her, its, our, their",
    questions: [
      { type: "mc", q: "This is ___ car. It's dirty. (belongs to me)", options: ["my", "your", "his"], answer: "my", exp: "Belongs to me → my." },
      { type: "mc", q: "Is that ___ watch? (belongs to you)", options: ["my", "your", "its"], answer: "your", exp: "Belongs to you → your." },
      { type: "mc", q: "Marco lost ___ keys.", options: ["his", "her", "its"], answer: "his", exp: "Marco = he → his." },
      { type: "mc", q: "Mia is in ___ studio.", options: ["his", "her", "its"], answer: "her", exp: "Mia = she → her." },
      { type: "mc", q: "The dog wagged ___ tail.", options: ["his", "her", "its"], answer: "its", exp: "Belongs to the object/animal → its." },
      { type: "mc", q: "This is ___ company. (belongs to us)", options: ["our", "their", "its"], answer: "our", exp: "Belongs to us → our." },
      { type: "mc", q: "That's ___ ball. (belongs to them)", options: ["our", "their", "its"], answer: "their", exp: "Belongs to them → their." },
      { type: "mc", q: "I love this restaurant. ___ pizzas are incredible.", options: ["Its", "Their", "His"], answer: "Its", exp: "Belongs to the restaurant (a thing) → its." },
      { type: "mc", q: "I love this neighborhood; ___ streets are quiet.", options: ["its", "their", "his"], answer: "its", exp: "Belongs to the neighborhood → its." },
      { type: "mc", q: "He lost ___ phone.", options: ["his", "her", "its"], answer: "his", exp: "He → his." },
      { type: "mc", q: "She forgot ___ umbrella.", options: ["his", "her", "its"], answer: "her", exp: "She → her." },
      { type: "mc", q: "We finished ___ homework.", options: ["our", "their", "its"], answer: "our", exp: "We → our." },
      { type: "mc", q: "They sold ___ house.", options: ["our", "their", "its"], answer: "their", exp: "They → their." },
      { type: "mc", q: "The cat licked ___ paw.", options: ["his", "her", "its"], answer: "its", exp: "Belongs to the animal → its." },
      { type: "mc", q: "Is this ___ pen? (talking to a friend)", options: ["my", "your", "its"], answer: "your", exp: "Belongs to you → your." },
      { type: "mc", q: "I like ___ new haircut! (talking to a friend)", options: ["my", "your", "its"], answer: "your", exp: "Belongs to you → your." },
      { type: "mc", q: "Sarah brought ___ own lunch.", options: ["his", "her", "its"], answer: "her", exp: "Sarah = she → her." },
      { type: "mc", q: "The company changed ___ logo.", options: ["his", "her", "its"], answer: "its", exp: "Belongs to the company (a thing) → its." },
      { type: "mc", q: "Ivan and Daria love ___ apartment.", options: ["our", "their", "its"], answer: "their", exp: "Belongs to them → their." },
      { type: "mc", q: "I finished ___ lesson early today.", options: ["my", "your", "its"], answer: "my", exp: "Belongs to me → my." },
      { type: "mc", q: "He always brushes ___ teeth twice a day.", options: ["his", "her", "its"], answer: "his", exp: "He → his." },
      { type: "mc", q: "The bird built ___ nest in the tree.", options: ["his", "her", "its"], answer: "its", exp: "Belongs to the animal → its." }
    ]
  },
  {
    id: "its-vs-its",
    name: "it's vs. its",
    icon: "🔤",
    description: "Contraction (it is) vs. possession",
    questions: [
      { type: "mc", q: "___ raining outside.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The cup lost ___ handle.", options: ["it's", "its"], answer: "its", exp: "Possession → its (no apostrophe)." },
      { type: "mc", q: "___ my favorite book.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The company changed ___ policy.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ getting late.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "This restaurant is famous for ___ pizza.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ very hot today.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The dog wagged ___ tail happily.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ been a long day.", options: ["It's", "Its"], answer: "It's", exp: "It's = it has (contraction)." },
      { type: "mc", q: "Look at that car — ___ color is amazing.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ a beautiful morning.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The cat licked ___ paw.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "I think ___ going to rain.", options: ["it's", "its"], answer: "it's", exp: "it's = it is." },
      { type: "mc", q: "This phone lost ___ charger.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ not fair!", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The team celebrated ___ victory.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ time to go.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "Every rule has ___ exception.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ okay, don't worry.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "The company increased ___ profits.", options: ["it's", "its"], answer: "its", exp: "Possession → its." }
    ]
  },
  {
    id: "pronouns",
    name: "Subject vs. Object Pronouns",
    icon: "🙋",
    description: "I/me, he/him, she/her, we/us, they/them",
    questions: [
      { type: "mc", q: "___ kicked the ball. (he does the action)", options: ["He", "Him"], answer: "He", exp: "Subject (does the action) → he." },
      { type: "mc", q: "She kicked ___. (action happens to him)", options: ["he", "him"], answer: "him", exp: "Object (receives the action) → him." },
      { type: "mc", q: "___ love pizza. (I do the action)", options: ["I", "Me"], answer: "I", exp: "Subject → I." },
      { type: "mc", q: "Give it to ___. (action happens to me)", options: ["I", "me"], answer: "me", exp: "Object → me." },
      { type: "mc", q: "___ is my teacher. (she does the action)", options: ["She", "Her"], answer: "She", exp: "Subject → she." },
      { type: "mc", q: "I saw ___ yesterday. (action happens to her)", options: ["she", "her"], answer: "her", exp: "Object → her." },
      { type: "mc", q: "___ are my friends. (they do the action)", options: ["They", "Them"], answer: "They", exp: "Subject → they." },
      { type: "mc", q: "I called ___ last night. (action happens to them)", options: ["they", "them"], answer: "them", exp: "Object → them." },
      { type: "mc", q: "___ works with me. (he does the action)", options: ["He", "Him"], answer: "He", exp: "Subject → he." },
      { type: "mc", q: "Can you help ___? (action happens to him)", options: ["he", "him"], answer: "him", exp: "Object → him." },
      { type: "mc", q: "___ live in Kyiv. (we do the action)", options: ["We", "Us"], answer: "We", exp: "Subject → we." },
      { type: "mc", q: "Please join ___. (action happens to us)", options: ["we", "us"], answer: "us", exp: "Object → us." },
      { type: "mc", q: "___ is a good student. (she does the action)", options: ["She", "Her"], answer: "She", exp: "Subject → she." },
      { type: "mc", q: "The teacher gave ___ homework. (action happens to her)", options: ["she", "her"], answer: "her", exp: "Object → her." },
      { type: "mc", q: "___ went to the store together. (they do the action)", options: ["They", "Them"], answer: "They", exp: "Subject → they." },
      { type: "mc", q: "Between you and ___, this is a secret. (action affects me)", options: ["I", "me"], answer: "me", exp: "After a preposition, use the object form → me." },
      { type: "mc", q: "___ told me the news. (they do the action)", options: ["They", "Them"], answer: "They", exp: "Subject → they." },
      { type: "mc", q: "Listen to ___! (action happens to me)", options: ["I", "me"], answer: "me", exp: "Object → me." },
      { type: "mc", q: "___ is my dog.", options: ["It", "Its", "It's"], answer: "It", exp: "Subject pronoun → It." },
      { type: "mc", q: "I feed ___ every morning. (the dog)", options: ["it", "its"], answer: "it", exp: "Object pronoun → it." },
      { type: "mc", q: "___ helped us yesterday. (you do the action)", options: ["You", "Your"], answer: "You", exp: "Subject → You." },
      { type: "mc", q: "We invited ___ to the party. (action happens to you)", options: ["you", "your"], answer: "you", exp: "Object → you (same form as subject)." }
    ]
  },
  {
    id: "plural-agreement",
    name: "Plurals & Agreement",
    icon: "🔢",
    description: "Cats are cute, water/fish/sheep, general truths",
    questions: [
      { type: "mc", q: "Choose the correct sentence:", options: ["Cat is cute.", "Cats are cute."], answer: "Cats are cute.", exp: "General statements about a group use the plural noun." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Winters are boring.", "Winter are boring."], answer: "Winters are boring.", exp: "Plural subject needs 'are'." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Apple juice are tasty.", "Apple juice is tasty."], answer: "Apple juice is tasty.", exp: "'Apple juice' is uncountable → is." },
      { type: "mc", q: "Choose the correct plural of \"fish\":", options: ["fishs", "fish", "fishes"], answer: "fish", exp: "Fish is the same in singular and plural." },
      { type: "mc", q: "Choose the correct plural of \"sheep\":", options: ["sheeps", "sheep"], answer: "sheep", exp: "Sheep is the same in singular and plural." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Waters is on the table.", "Water is on the table."], answer: "Water is on the table.", exp: "Water is uncountable, no 's' → is." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Dogs is loyal.", "Dogs are loyal."], answer: "Dogs are loyal.", exp: "Plural subject needs 'are'." },
      { type: "mc", q: "Choose the correct sentence:", options: ["My cat Bobby is cute.", "My cat Bobby are cute."], answer: "My cat Bobby is cute.", exp: "One specific cat = singular → is." },
      { type: "mc", q: "Choose the correct sentence:", options: ["This winter is boring.", "This winters is boring."], answer: "This winter is boring.", exp: "'This' + singular noun." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Christmas are wonderful.", "Christmas is wonderful."], answer: "Christmas is wonderful.", exp: "Christmas is treated as singular." },
      { type: "mc", q: "Choose the correct sentence:", options: ["John is tall.", "John are tall."], answer: "John is tall.", exp: "One person = singular → is." },
      { type: "mc", q: "Choose the correct plural of \"child\":", options: ["childs", "children", "childes"], answer: "children", exp: "Child → children (irregular plural)." },
      { type: "mc", q: "Choose the correct plural of \"person\":", options: ["persons", "people", "peoples"], answer: "people", exp: "Person → people (irregular plural)." },
      { type: "mc", q: "Choose the correct sentence:", options: ["The flamingos is pink.", "The flamingos are pink."], answer: "The flamingos are pink.", exp: "Plural subject needs 'are'." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Flamingos eats fish.", "Flamingos eat fish."], answer: "Flamingos eat fish.", exp: "Plural subjects use the base verb (no -s)." },
      { type: "mc", q: "Choose the correct sentence:", options: ["My chairs is new.", "My chairs are new."], answer: "My chairs are new.", exp: "Plural subject needs 'are'." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Evolution create things.", "Evolution creates things."], answer: "Evolution creates things.", exp: "'Evolution' is singular/uncountable → creates." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Trees are weird.", "Trees is weird."], answer: "Trees are weird.", exp: "Plural subject needs 'are'." },
      { type: "mc", q: "Choose the correct sentence:", options: ["These regulation are different.", "These regulations are different."], answer: "These regulations are different.", exp: "'These' needs a plural noun." },
      { type: "mc", q: "Choose the correct sentence:", options: ["The books is on the table.", "The books are on the table."], answer: "The books are on the table.", exp: "Plural subject needs 'are'." }
    ]
  },
  {
    id: "mixed",
    name: "Mixed Review",
    icon: "🎯",
    description: "A little bit of everything, all mixed together",
    questions: [
      { type: "mc", q: "She is ___ honest person.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "___ books on the shelf are mine.", options: ["This", "These", "Those"], answer: "These", exp: "Near + plural → these." },
      { type: "mc", q: "The company lost ___ best employee.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "fill", q: "Marco ___ (not / own) a car.", answers: ["doesn't own", "does not own"], exp: "he → doesn't + base verb." },
      { type: "mc", q: "___ you ready?", options: ["Am", "Is", "Are"], answer: "Are", exp: "you → Are." },
      { type: "fill", q: "My wife always ___ (brush) her teeth before bed.", answers: ["brushes"], exp: "she → brushes." },
      { type: "mc", q: "Sarah gave the book to ___. (action happens to him)", options: ["he", "him"], answer: "him", exp: "Object pronoun → him." },
      { type: "mc", q: "___ mountains over there are beautiful.", options: ["That", "Those", "These"], answer: "Those", exp: "Far + plural → those." },
      { type: "mc", q: "The twins ___ rarely late.", options: ["am", "is", "are"], answer: "are", exp: "Plural subject → are." },
      { type: "mc", q: "I need ___ hour to finish.", options: ["a", "an", "the"], answer: "an", exp: "Silent h → vowel sound → an." },
      { type: "mc", q: "This is ___ chair; I sit here every day.", options: ["my", "your", "its"], answer: "my", exp: "Belongs to me → my." },
      { type: "fill", q: "The flamingo ___ (eat) fish every day.", answers: ["eats"], exp: "it → eats." },
      { type: "mc", q: "___ raining, so take an umbrella.", options: ["It's", "Its"], answer: "It's", exp: "It's = it is." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Cats are cute.", "Cat is cute."], answer: "Cats are cute.", exp: "General statements use the plural noun." },
      { type: "mc", q: "He works as ___ accordion player.", options: ["a", "an", "the"], answer: "an", exp: "Vowel sound → an." },
      { type: "mc", q: "The dog wagged ___ tail when it saw me.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "___ people over there are my classmates.", options: ["This", "These", "Those"], answer: "Those", exp: "Far + plural → those." },
      { type: "fill", q: "My neighbors ___ (not / watch) football.", answers: ["don't watch", "do not watch"], exp: "they → don't + base verb." },
      { type: "mc", q: "I go to the gym ___ a week. (not very often)", options: ["always", "twice", "never"], answer: "twice", exp: "Twice a week = low frequency." },
      { type: "mc", q: "Give it to ___. (action happens to me)", options: ["I", "me"], answer: "me", exp: "Object pronoun → me." },
      { type: "mc", q: "The twins aren't ___ noisy. (90%)", options: ["always", "usually", "never"], answer: "usually", exp: "90% = usually." },
      { type: "mc", q: "Choose the correct plural of \"person\":", options: ["persons", "people"], answer: "people", exp: "Person → people (irregular)." },
      { type: "mc", q: "___ is my dog.", options: ["It", "Its"], answer: "It", exp: "Subject pronoun → It." },
      { type: "mc", q: "The bird built ___ nest in the tree.", options: ["his", "her", "its"], answer: "its", exp: "Belongs to the animal → its." },
      { type: "fill", q: "She ___ (know) his number.", answers: ["knows"], exp: "she → knows." },
      { type: "mc", q: "___ Earth orbits the sun.", options: ["A", "An", "The"], answer: "The", exp: "Only one Earth → the." },
      { type: "mc", q: "Choose the correct sentence:", options: ["Pickles sometimes grabs my socks.", "Pickles grabs sometimes my socks."], answer: "Pickles sometimes grabs my socks.", exp: "Adverb of frequency goes before the main verb." },
      { type: "mc", q: "We invited ___ to the party.", options: ["you", "your"], answer: "you", exp: "Object pronoun 'you' looks the same as the subject form." },
      { type: "mc", q: "This restaurant is famous for ___ pasta.", options: ["it's", "its"], answer: "its", exp: "Possession → its." },
      { type: "mc", q: "Choose the correct plural of \"child\":", options: ["childs", "children"], answer: "children", exp: "Child → children (irregular)." }
    ]
  }
];
